### ISSUE TITLE
Topics Content Change

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1128]
Please change the content in Topics to reflect either Topics (meaning any kind of Topic), Node Topics (a dynamic way of organizing threads where threads have one Topic and is a direct relationship with an existing forum node), or Thread Topics (a dynamic way of organizing threads, with threads having multiple Topics). For example right now in options it says things like Number of topics to show when creating thread, Number of topics selectable from same group, etc. They should say Thread Topics instead of topics. Topics should also always be capitalized. Also, we should probably rename the widgets from [TH] Topics: Forum filter and [TH] Topics: Topic filter to [TH] Topics: Node Topics and [TH] Topics: Thread Topics. Let me know if you have any questions.

**Comment by jonw316** [comment]
Regarding capitalization of the word Topics, there was a convention introduced in XF 2.0 that nothing is ever capitalized other than the first word, so there is no more Title Case or anything like that, so it would look a bit strange for the word Topic to be capitalized in forms and titles on the front end. In XF1, it was almost the complete opposite and almost everything was capitalized.

The only exception would be if we were referring to the name of the add-on, i.e. "In order to enable topic filters on trending threads, you must have the Topics and Trending add-ons installed.".

Having said that, as far as marketing material or external documentation, I think it would be fine to use the capitalization you have suggested. In fact, I think that works well.

**Comment by victoriad1** [comment]
Thanks for the clarification. That makes sense. Just so we are on the same page though in your example "In order to enable topic filters on trending threads, you must have the Topics and Trending add-ons installed.". It should say "thread topics" instead of "topic filters".

**Comment by jonw316** [comment]
Ah yes, oops.
