### ISSUE TITLE
[TH] Topics - Filters are not remove automatically

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1193]
Filters are not remove automatically, when closing or going to another forum. Filters should be removed when going to another forum.

See here:  https://giant.gfycat.com/RawActualEuropeanfiresalamander.webm

**Comment by jonw316** [comment]
This is as designed.

**Comment by Nirjonadda** [comment]
This is as designed? Then can be provide a option for this? This design can be call bug.

**Comment by jonw316** [comment]
It has always been the case that once a filter is selected it stays selected on all other pages until you deselect it. I'm not sure why you think this is a bug.

**Comment by Nirjonadda** [comment]
because this bug, when i close the page then view another forum should not interfere with any filter, if i am not select any thing. If you still like are this happen then please provide a option for this.

**Comment by jonw316** [comment]
It is not possible to add such an option.

**Comment by Nirjonadda** [comment]
Also this are OK for in Topics list, not in forum list.

OK for `/forums/-/all-threads?topics=Main+forum.1`

Not OK for `/forums/main-forum.2/`

Also when viewing via Topics list then this automatic filter also interfere with forum list.

See here: https://giant.gfycat.com/RawActualEuropeanfiresalamander.webm

**Comment by mikecreuzer** [comment]
It is indeed as designed but @Nirjonadda is not the first to be concerned with this. 

@jonw316 simply put is there a way we can have filter reset on page load as a setting?

**Comment by jonw316** [comment]
Simply put, no.

**Comment by mikecreuzer** [comment]
Couldn't you run the clear topics function on page load?

**Comment by jonw316** [comment]
If only it were that simple.

**Comment by mikecreuzer** [comment]
Ill try to bug you on this later and see how its built, @Nirjonadda is not the first to think this is a bug. I wanted it as it felt more natural to me to keep features across the page. 

For the record, though I dont know how its done, I do see how like clicking the create thread button could not know what topic is selected. not sure if there are other cases. But if so, then simply just not saving the cookie would not save the filter. Then we could put a setting to wrap that cookie.

For now if you're really sure then Ill assume the reason is compelling.
