### ISSUE TITLE
Topics Widgets

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1203]
For the Topics widgets, it should always show horizontal on mobile above the content. There should also be a way to control where the desktop one goes and if you remove it the mobile one should be removed as well. There are too many steps to set up the widgets properly and keep them in sync. 

@Ian-Hitt

**Comment by mikecreuzer** [comment]
Yeah this can be a discussion, I get why jon did it but to me these are the concerns I see:

1. People have to keep widget locations for their horiz/vert ones in sync (which they can easily screw up)
2. Mobile isnt defined, it should be at a breakpoint value to show, breakpoint value to hide (with defaults for what we recommend as description maybe)
3. Ian originally had the horiz just always above the thread list, and to me this is appealing.

Open to thoughts on this

**Comment by jonw316** [comment]
I think having the horizontal scroller as a widget is right, but I agree it takes too long to setup at the moment and can be a bit confusing.

I think the solution to this and some of the other problems we've had is:

- [ ] Have more widgets enabled by default -- at the moment the horizontal one isn't there by default, so we need to make it at least behave by default as Ian originally designed it. This was always my intention.
- [ ] Have a single widget for Thread Topics and Node Topics that can be set to either Default, Thread Topics or Node Topics. Default = Node Topics if Thread Topics is disabled or Thread Topics otherwise. Default by default. This means the Node widget should also be able to work as a horizontal scroller, which was always my intention.
- [ ] The option should be "Hide on mobile devices if horizontal widget is visible" instead of just "Hide on mobile devices" and "Only show on mobile devices if vertical widget is visible" instead of just "Only show on mobile devices".
- [ ] Make it clearer (with a link probably) that 'Mobile' is defined by the breakpoint value in style properties.

**Comment by jonw316** [comment]
<img width="802" alt="screenshot 2018-11-30 at 12 21 12" src="https://user-images.githubusercontent.com/42781420/49289053-716e6000-f49a-11e8-8ae9-61122e20a732.png">

On install, we will add a widget with the above default settings to every possible widget position that supports topic filtering.

**Comment by jonw316** [comment]
1. I'm going to go through all the positions and create any extras as necessary, then I'll add the default positions for new installs at the same time.

2. This sounds like a Javascript issue. I'll check on this.

3. I'll check on this.

**Comment by jonw316** [comment]
2. #1216
3. #1217
