### ISSUE TITLE
Detect if large site, then prompt to use cmdline

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1218]
Not sure how feasible, but a customer had some issues due to this not being clear. On reactions, instead of prompting install, could we request he run `php cmd.php xf:addon-install Themehouse/Reactions` or something?

**Comment by JakeBooher** [comment]
Large sites can install Reactions just fine using the admin install tool, it doesn't do anything crazy during installation. The issue it had during installation was due to a server configuration issue (specifically installing a **very** heavy dev tool on a production server -- which comes with countless other downsides, including various security issues)

**Comment by mikecreuzer** [comment]
The customer said that Xon's does this check, which I don't understand, seems oddly specific I agree, but Im out of my element in knowing if this matters.

**Comment by JakeBooher** [comment]
It's been installed, without issue, on 15 million post sites. If this add-on were to cause issues on install for a 1 million post site so would countless others, the install script doesn't do any heavy lifting
