### ISSUE TITLE
[Nodes] Remove .has-flexbox class as no longer exists in XF 2.1

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1356]

**Comment by JakeBooher** [comment]
I'm pretty sure the nodes add-on uses this pretty heavily, so I don't think we want to just remove the class. They've just removed Modernizr from being initialized and have added their own framework. We'll want to use that to add back the `has-flexbox` class so we can apply the flexbox styling only if it's available: https://xenforo.com/community/threads/what%E2%80%99s-new-for-developers-in-xf-2-1.155536/#post-1292587

**Comment by jonw316** [comment]
By the looks of it, we don't seem to support people who don't have flexbox support particularly well, so maybe that needs fixing too.

**Comment by Ian-Hitt** [comment]
XF removd modernizr in 2.1. They no longer support the browsers that used it

**Comment by jonw316** [comment]
So I guess the only question is whether it is worth leaving in for XF 2.0 (having a conditional or something), or just removing it completely in the next version?

**Comment by JakeBooher** [comment]
> Only .33% of browser usage don't support it now

Not sure where this number came from, everything I've seen has it closer to 3-4% that don't support it.

**Comment by kylerc** [comment]
Looking over some of the use stats for browsers, there is still around 4% that doesn't support flexbox.  That's a low amount but still not zero.   

At some point supporting that small number of users probably isn't worth the degradation to the vast majority's experience by default (loading in modernizr, running that before content shows, loading in extra styling for various fallbacks, fewer JS polyfills, etc) if XF itself isn't supporting it either, but I don't quite think we're there yet. I think what we'll likely want to do instead is have a toggle for this as a SP that will include modernizr, polyfills, etc to support older versions of IE since UI.X as a framework gets used on enough large sites that we probably still want support for those users.  This would let us maybe even release a UI.X lite child theme if we wanted that could be quickly added below a custom style to handle older browsers even more effectively.

In either case, since for now since we largely have XF2.0 working fine without flexbox, let's keep that supported.

**Comment by jonw316** [comment]
It looks like we don't actually support XF2.0 without flexbox currently. It just comes out as a big mess.

**Comment by JakeBooher** [comment]
> loading in modernizr, running that before content shows, loading in extra styling for various fallbacks, fewer JS polyfills, etc

FWIW, no need to load in the entirety of Modernizr for just that, XenForo 2.1 has a feature test library that you can use to add test for specific features that you need with much less overhead than all of Modernizr for one check

**Comment by Ian-Hitt** [comment]
So regarding this issue, would we do modernizr change in both UI.X as well as Nodes, and any other add-ons that may need it?

**Comment by kylerc** [comment]
@Ian-Hitt I think we'll want to see how that is needed on a case by case.  I'll assume that UI.X will need the sp for it since it has a fair amount of styling associated with it.  Some addons will likely also need it.  For actual use, we'll see if it's possible to support just by enabling one or the other (for example, UI.X might do enough that we can turn it off for some addons) but we'll have to see how that ends up going once we do the implementation.  If that ends up being the case we'll want to make sure it is documented.

**Comment by jonw316** [comment]
For now, I've just put a conditional around the .has-flexbox class so that it doesn't get added in XF 2.1, so no XF 2.0 sites are going to lose support for older browsers.
