### ISSUE TITLE
[Topics] Overlapping icons/tooltip on hover for Topics on thread bit

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1550]
![image](https://user-images.githubusercontent.com/1217271/53600283-ce97b180-3b6e-11e9-8351-6fa073d99bde.png)

**Comment by Chazza** [comment]
I noted a similar bug for this in a issue a little while ago. However it was the ‘watch’ icon overlapped.

**Comment by jonw316** [comment]
#1523

**Comment by mikecreuzer** [comment]
@jonw316 reason I assigned you as its probably best fixed soon. 

Might be a few ways, but one qucik fix is find:

`.structItem-topicList:hover` in the topics css file and add `z-index: 1;` to that

**Comment by victoriad1** [comment]
Not sure if this is related or not but on a thread list, when you hover over the thread topics on a thread, the thread topics expand to cover up the thread title if there are more topics than space. It seems to be/not be an issue as the screen size changes. It might not be an issue though because I'm not sure what should happen at a smaller screen size. The spacing between elements (replies, views, date/time, and user) seems to have extra spacing as well.
