### ISSUE TITLE
[ReactPlus] Undo Reaction by clicking on the left side display of reactions on a message

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#178]
@JakeBooher Says this is a fairly large project to do in an efficient way, going to be done at a later date.

**Comment by LukasWieditz** [comment]
@JakeBooher did you plan this for ReactPlus?

**Comment by JakeBooher** [comment]
Assuming it's something I can do reasonably without hacking it into working with the potential of it breaking, yeah. But unfortunatley I don't think that is going to be feasible because of [this](https://xenforo.com/community/threads/2-1-reactions-are-not-easily-extended.158764/). Unfortunately, it doesn't seem like they are interested in changing this either...
