### ISSUE TITLE
[TH] Donate 1.1.2 - Rolled back some functionality (again) - Minimum amounts

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1805]
As per issue #1770 this suggestion was actually implemented in 1.1.1 PL 1 and now it's mysteriously gone and we're back to having the minimum amount defaulted into the amount input field. 

Just curious what the logic is behind putting it in then removing it twice now without a mention in the changelog (or is this a code merge issue). 😕

**Comment by JakeBooher** [comment]
Is that the right issue? That one wasn't implemented, just provided instructions to make the change yourself if wanted

**Comment by ichpen** [comment]
It was implemented properly in the previous version. Now it's gone. So wondering if it's something I said :)

**Comment by JakeBooher** [comment]
I've just checked and the 1.1.1 Patch Level 1 update I released only touched Setup.php to fix an issue with fresh installs, had no changes to templates or any change that would have impacted someone with an existing install at all

**Comment by ichpen** [comment]
I don't know what to tell you Jake. I can restore a backup of my forum and show you but I definitely didn't dream it up as I even sent you some virtual kudos for putting it in. It's not the end of the world but that's basically what happened.

Maybe it was an older residual template that was not replaced by a subsequent version? Don't know.

**Comment by JakeBooher** [comment]
If it was included in that version it definitely wasn't intentional and could have been because it was packaged with the template changes still in place from when I provided the solution (which wouldn't be desired as there was no phrase anyways) so the current state is still intended I think, and our recommendation would be to implement the template changes I mentioned in that other issue :)
