### ISSUE TITLE
[TH] Donate: Improve current styling of progress/ goal boxes

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#200]

**Comment by LukasWieditz** [comment]
I think we have this with #315 #366 & #252

**Comment by mikecreuzer** [comment]
<img width="312" alt="screen shot 2018-05-22 at 4 22 24 pm" src="https://user-images.githubusercontent.com/1217271/40390947-704cbd7a-5ddc-11e8-9f80-0e33a1c261a3.png">

- [ ] Full width or at least centered button
- [ ] Black text on colored background. We should redo the html here since we cannot do a blend mode and honestly its just not good html
- [ ] Donation ends text looks, thrown together. We can do better

Overall lets redo HTML, this isnt good.

**Comment by LukasWieditz** [comment]
We had an issue on your latter picture in #249. Ian closed it, so I assumed it was done.

**Comment by LukasWieditz** [comment]
>  The title of the widget should just be 'Donate' I assume? Unless this is configurable, but why does it say [TH] etc

The title is prefixed with `TH` just as all our widget definitions are. Widget titles are individually configurable.
