### ISSUE TITLE
Topic filter on trending page

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#266]
Make topics filterable on trending page, including live/ajax update of list

**Comment by mikecreuzer** [comment]
We need a concept of a unified "filter/tab" bar. @JakeBooher and I discussed this some time ago and thought about making it its own add-on, but idk the best thing to do here. It could fit inside of trending or topics even really. Im still not sure since it needs to work with topics AND trending alike.

The features for this would be:

1. Add/edit tabs (such as: custom, forum list, trending, new posts, new media, topics, etc.)
2. Set default tab and user editable (so people can choose between trending or forum list for example)
3. Filter out certain topics on the homepage (filter sidebar is an obvious one, but also things like "following" "replied to" "posted today" etc

Any ideas @LukasWieditz ?

**Comment by LukasWieditz** [comment]
I'm not sure if we want to really keep/force the filters and the tabs in the same place? The topics filter widget obviously fits best with the topics add-on, but the tabs is probably suited best to be placed in a different add-on, if you want to have it available for both.

We could develop some sidebar widget that could be placed potentially everywhere and provide topics filters for all topics, including live repolling, where applicable (via data-attributes or similar). We could provide a unified route (topics/filtered) or so, that would allow to poll a specific list of topics to anywhere we need them. That way we could for example live-repoll from inside the trending page by handing the selected topics and the trending sort order to the function, or from the find own threads page by providing the latest posts sort order and the user filter.
