### ISSUE TITLE
Improvements to topic user title

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#332]
<img width="1329" alt="screen shot 2018-05-14 at 10 11 32 am" src="https://user-images.githubusercontent.com/1217271/40006150-44a0cfd2-575f-11e8-8cba-40d73e293069.png">

- [x] If a topic has a color (which I assume most will) then change button to be like a white border type of thing or white background (where white could be black if the topic color is really light)
- [x] Extra reminder for some subtle mobile improvements (note the CTA and general flow of content is ugly)
- [x] I prefer full-width titlebar as opposed to a wrapped one
- [x] Label has same bg as background, which makes sense. But maybe one of them should be darkened/lightened a bit to make label stand out just slightly (5-10%)
- [x] Margin between title and description is greater than the padding around the entire thing so it looks odd

**Comment by Ian-Hitt** [comment]
.5 this uses the markup and styling from the default theme, which is also flawed in this way. its because the button and title are in the same component. in UI.X i re-arranged it so that it floats to the right of all titlebar content instead, but since this is an add-on i presume it should bet the same as the default theme? Suppose I can change it to use UI.X markup specifically in UI.X

**Comment by mikecreuzer** [comment]
Re-opening for a few reasons:

1. Mask not as discussed yesterday (darker and breakpoint should start earlier for when it begin to turn to black (50% I think, then you can make opacity from .4 to maybe .6)
2. Its not full width titlebar, I much prefer that.
3. I think if you're going to center the button on mobile, you should center everything.
4. The padding I think should be bumped up at least around the entire cover.
