### ISSUE TITLE
Developer info missing

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#415]
Developer info missing for [TH] Post Comments and [TH] Topics.

![screenshot00091](https://user-images.githubusercontent.com/6899856/40449288-5cb34926-5ed8-11e8-97ca-6b0df1ee2919.png)

**Comment by mikecreuzer** [comment]
<3 great spot thank you so much :D

**Comment by LukasWieditz** [comment]
@mikecreuzer Still need the icon for Post Comments and some short description for both, Topics and Post Comments.

**Comment by mikecreuzer** [comment]
"Show how you feel with a single click" change to: 

"Additional like button emojis to add extra meaning, boost user interaction, and add to the fun!"

And as for Topics:

"A content discovery and organizational tool allowing content to be found using multiple topics instead of just one node."

@nikkiradloff will have the icon

**Comment by LukasWieditz** [comment]
Post Comments, not reactions, but I'll change reactions as well.

**Comment by mikecreuzer** [comment]
Ah right:

"A structural modification for turning posts into threaded mode where replies are nested."

**Comment by LukasWieditz** [comment]
Description is in. Waiting for the icon, then we can close this ticket.

**Comment by mikecreuzer** [comment]
Nikki is sending these to Lukas direct, so closing
