### ISSUE TITLE
[TH] Nodes - Option to manage Sub-Forum maximum columns

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#543]
Same as regular forums, allow sub-forums to have their own grid options.

**Comment by mikecreuzer** [comment]
I should be able to choose a min-width essentially which gives me the grid, but not actually choose a column. @Ian-Hitt I feel like you probably did this already? 

If I say choose 400px I may get 2 columns on desktop, but otherwise 1 on mobile/tablet. if I choose 180px, I should get 2 columns on pretty much every device.

Please close if so @Ian-Hitt
