### ISSUE TITLE
Use cookies for guests when they set a topic

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#601]
Navigation back should keep the topic selected - may want to keep cookies for logged in users as well? not sure. Just take the value from db and store in cooke.

**Comment by kylerc** [comment]
This would ideally save per user on the server if possible.  Otherwise it would have to load the page, have the cookie request the filtered topics, and wait for that to also load in.  Especially on mobile that could add a few hundred ms to page load times.  I think that Jake has saved guest preferences on the server before but I can't remember the implementation details for that.  @LukasWieditz would you be familiar with how to do that?

**Comment by JakeBooher** [comment]
We probably don't want to randomly create cookies for things if at all possible, would be much better to use the session to define these changes, and it'd work for both guests and registered users

**Comment by mikecreuzer** [comment]
Point is that guests do browser forums, and topics aren't kept. Its small, but worth fixing.
