### ISSUE TITLE
When unreacting all, clicking confirm throws error

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#708]
`Provided react ID not found` on `/reactions/unreact/`

Possible due to an upgrade or something, but worth noting nonetheless

**Comment by jonw316** [comment]
This also happens if you delete a reaction.

I can fix this error, but there are also other undesirable effects if you delete a reaction that has been used.

Do we want to remove the ability to delete reactions that have been used?

**Comment by mikecreuzer** [comment]
Just so Im clear, the issue I posted is when someone Unreacts. Ill assume thats not a tough issue?

But regarding deleting a reaction, meaning from the ACP, I see what you mean as I assume we're discussing caches on all posts?

Two ways I see that: 

Deleting just hides it, but data is kept. 
Deleting goes through and deletes all data for that reaction in some process.

I dont know which is better.

**Comment by jonw316** [comment]
Yes, fixing the unreacts error is relatively easy.

As for the wider issue: at the moment, we seem to be doing the hiding it option. Rather than "delete", we should really call this "disable" and the delete option should actually go through and delete all data (which may not be so easy to do!). Removing the delete option for used reactions might be easier in the short term.

**Comment by mikecreuzer** [comment]
Up to you and @LukasWieditz Im ok either way

**Comment by LukasWieditz** [comment]
We do have a service/job that deletes all reactions from the database for a specific user. It's currently only triggered when a user is deleted though. I guess we can modify that depending on the needs of the task.
