### ISSUE TITLE
[Topics] Recursively assign nearest Topics to select nodes

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#863]
Ill let Kyler explain this a bit, but ultimately we need a way to assign existing threads to the topic setup of choice, AND rebuild that should we make changes to Topics.

**Comment by kylerc** [comment]
Sure, basic idea is to use this as a way to quickly apply topic information to threads that are sorted in the default XF node hierarchy.  If you imagine that node hierarchy as a tree with the root at the top branching down to level 0 nodes / forums branching down to level 1 nodes forums, etc my thought was to show this hierarchy (likely similar view to the node sort view) and allow admins to assign 1 or more topics to any node (as well as the root).  Each thread would traverse up through the node tree to find the nearest node that the admin has assigned topics to and would then get those topics.  This would allow for a fairly minimal set of actions to mass-assign topics to all threads on a site and speed up on-boarding quite a bit.

**Comment by jonw316** [comment]
@mikecreuzer Is this priority?

**Comment by jonw316** [comment]
I'm not sure I fully understand this.

Are we saying that we should actually move the thread to a different node if the node it is in doesn't have any topics? This would then leave any nodes without a topic completely empty once the tool has been run.

Are there admins out there that actually want this?

**Comment by kylerc** [comment]
Hmm that's a fair question.  My goal was to quickly transition a node structure that was bad for topics (deeply nested, too many nodes, etc) to one that was simplified and would work well with topics with this process, but you're right that I'm not sure if moving the actual threads is the right choice since that'd cause issues if the admin every disabled topics.  I'm not familiar enough with the technical implementation of things, but how hard would it be to have multiple nodes associated with a single topic, at least for legacy (before topics) threads?  Not sure if that makes sense or if there's a better solution.

**Comment by jonw316** [comment]
> but how hard would it be to have multiple nodes associated with a single topic
Probably impossible without a complete re-write.
