### ISSUE TITLE
Add thTopic--primary to main topic in topic header

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#894]
Main topic in topic header needs `.thTopic--primary` class to diffrentiate styling between the primary topic and secondary topic on thread view

**Comment by Ian-Hitt** [comment]
Should fix this issue:
<img width="602" alt="screen shot 2018-10-09 at 4 58 33 pm" src="https://user-images.githubusercontent.com/15836384/46701207-935b0d00-cbe4-11e8-9485-7fb688f9c002.png">

**Comment by LukasWieditz** [comment]
Adding that to the template yourself would've taken as long as creating this ticket...

**Comment by jonw316** [comment]
I've removed the whole concept of "primary" as it adds an extra level of complexity where we seemed to have "primary", "secondary" and "neither primary or secondary", even though there was no such thing. Secondary in this context is now also called "additional", to avoid using different terminology in different places.

Are you able to use :first or :not(.thTopic--additional) or set it up so that additional topics (those with class .thTopic--additional) inherit from .thTopic?

**Comment by mikecreuzer** [comment]
This is still a visual bug tho.

**Comment by jonw316** [comment]
The issue is with the UI.X theme, not with Topics.

**Comment by Ian-Hitt** [comment]
@jonw316 The CSS for this is already there (in Covers specifically.) tThe issue is that the class was removed.

**Comment by jonw316** [comment]
Covers then, sorry. Can you change the CSS in Covers? I don't want to add that class back.
