### ISSUE TITLE
Topics (actualy Topics) support for And and OR setting at filter widget level

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#970]
I think we discussed this Jon. Wont make sense for node one of course, but for Topics we could. Default should be AND as it is currently

**Comment by jonw316** [comment]
I don't think this is going to be possible to do at the widget level easily because you can have multiple widgets/widget-like elements on the same page and there cannot be a mix of AND and OR on one page.

Personally I think it is fine as is, but we could do an option in the global options if you think that would be useful?

**Comment by mikecreuzer** [comment]
Global option is fine by me yeah.

**Comment by jonw316** [comment]
Ok. I'll just do that, then it is ready to go...
