### ISSUE TITLE
Post Comments - pagination issue

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#996]
```
The first one, if there are a lot of post (300-400) in a thread, or so, I mean there are 58 pages in a thread. However, page nav item displays 60 and you can only view 58. When click to 60, it redirects to 58 again. When click to last post in thread list, it redirects to 58 again. When click to the last post (or unread post, it doesn't matter) in new posts page, it redirects to 58 again and you can't see last post in thread. Interesting. As a result of this, Item Page Nav doesn't work properly. Meanwhile rebuild threads and post depth conflicts each other.
```

I suspect this is because we've left pagination as it is by default mostly and query a total of all posts in the thread rather than just the root level posts

**Comment by LukasWieditz** [comment]
The pagination is built from the message position, not the number of posts. I'd assume that his message positions are somewhat out of sync. He should try to rebuild them via `ACP > Tools > Data maintenance > Rebuild Caches > Rebuild post nesting` first.

**Comment by zethon** [comment]
I am definitely seeing this issue.

Here's how I've been able to recreate: 

(assume your pagination is 20 posts per page)

* Create a thread with multiple pages of content (let's say 5).
* On the last page (page 5), create exactly 20 posts (ie. so that any new post would be on a new page)
* Go back to a previous page and make a comment

You'll see that there are now "6" pages in the navigation but there's no way to navigate to page 6.

This is really bad because the thread then gets stuck in a weird state where you can't even view new posts in it. I am happy to show you on my board.

**Comment by jonw316** [comment]
I can't replicate this either. It must be conflicting with another add-on.

@zethon Do you have any other add-ons installed that might be affecting this?

**Comment by jonw316** [comment]
I was able to replicate this by disabling the Post Comments add-on. This is expected behaviour if you disable the add-on. You will need to rebuild the cache as Lukas has suggested in this case.

@zethon Can you confirm whether you had the add-on enabled or disabled when you experienced this?

**Comment by LukasWieditz** [comment]
Can maybe consider to queue a rebuild automatically upon disabling.
